"""Auto-generated by deploy.ipynb (section 3). DO NOT EDIT BY HAND.

Flat copy of the inference subset of src/ used by custom.py inside
the DataRobot DRUM container. The src/ package remains the source of
truth - re-run section 3 of deploy.ipynb after editing src/.

Concatenated from (in order):
  - src/config.py
  - src/utils.py
  - src/data/smiles_data.py
  - src/data/graph_features.py
  - src/data/loader.py
  - src/models/_scatter.py
  - src/models/pooling.py
  - src/models/sequence.py
  - src/models/dmpnn.py
  - src/training/trainer.py
"""

import os as _os

_os.environ.setdefault("USER", "drum")
_os.environ.setdefault("HOME", "/tmp")
_os.environ.setdefault("TORCHINDUCTOR_CACHE_DIR", "/tmp/torchinductor")
del _os

# ===== src/config.py =====

import yaml


def load_config(path_or_dict):
    """Load configuration from a YAML file path or return a dict directly."""
    if isinstance(path_or_dict, dict):
        return path_or_dict
    with open(path_or_dict) as f:
        return yaml.safe_load(f)


# ===== src/utils.py =====

import os
import random

import numpy as np
import torch

INPUT_PATH = "input/"
FEATURE_PATH = "feature/"
MODEL_PATH = "model/"
SUB_PATH = "sub/"


def seed_everything(seed=42):
    """Set random seeds for reproducible results across different libraries"""
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    os.environ["PYTHONHASHSEED"] = str(seed)

    try:
        import torch_geometric

        torch_geometric.seed_everything(seed)
    except ImportError:
        pass

    print(f"Random seed set to {seed} for reproducible results")


# ===== src/data/smiles_data.py =====

import math

from rdkit import Chem
import torch
from torch.utils.data import Dataset


class SMILESTokenizer:
    """Character-level SMILES tokenizer based on unique characters in dataset"""

    def __init__(self):
        self.special_tokens = {"<PAD>": 0, "<UNK>": 1, "<START>": 2, "<END>": 3}
        self.char_to_idx = self.special_tokens.copy()
        self.idx_to_char = {v: k for k, v in self.special_tokens.items()}

    def tokenize(self, smiles):
        """Tokenize SMILES string into characters"""
        return list(smiles)

    @staticmethod
    def _coerce_smiles(smiles):
        """Map missing / non-string values to '' so encode() never crashes.

        Graph featurization already returns a dummy graph for non-strings (NaN,
        None, pd.NA). Sequence scoring must do the same: DataRobot's custom
        model test injects nulls, and ``Series.tolist()`` turns them into
        ``float('nan')``, which ``list(nan)`` raises TypeError on.
        """
        return smiles if isinstance(smiles, str) else ""

    def fit(self, smiles_list):
        """Build vocabulary from unique characters in SMILES strings"""
        unique_chars = set()
        valid_count = 0
        for smi in smiles_list:
            if not isinstance(smi, str):
                continue
            try:
                mol = Chem.MolFromSmiles(smi)
            except Exception:
                continue
            if mol is None:
                continue
            unique_chars.update(set(smi))
            valid_count += 1

        print(f"Found {len(unique_chars)} unique characters in {valid_count} valid SMILES")
        print(f"Unique characters: {sorted(unique_chars)}")

        # Continue past whatever is already mapped rather than restarting at
        # len(special_tokens): re-fitting the same instance would otherwise
        # hand an id that is already taken to the first new character, so two
        # characters would share one embedding row.
        idx = max(self.char_to_idx.values()) + 1 if self.char_to_idx else 0
        for char in sorted(unique_chars):
            if char not in self.char_to_idx:
                self.char_to_idx[char] = idx
                self.idx_to_char[idx] = char
                idx += 1

        print(f"Vocabulary size: {len(self.char_to_idx)}")
        return self

    def encode(self, smiles, max_length=None):
        """Convert SMILES to character indices"""
        smiles = self._coerce_smiles(smiles)
        chars = self.tokenize(smiles)
        indices = [self.special_tokens["<START>"]]
        for char in chars:
            if char in self.char_to_idx:
                indices.append(self.char_to_idx[char])
            else:
                indices.append(self.special_tokens["<UNK>"])
        indices.append(self.special_tokens["<END>"])

        if max_length:
            if len(indices) > max_length:
                indices = indices[: max_length - 1] + [self.special_tokens["<END>"]]
            else:
                indices.extend([self.special_tokens["<PAD>"]] * (max_length - len(indices)))
        return indices

    def decode(self, indices):
        """Convert character indices back to SMILES"""
        chars = []
        for idx in indices:
            if idx in self.idx_to_char:
                char = self.idx_to_char[idx]
                if char not in ["<PAD>", "<START>", "<END>", "<UNK>"]:
                    chars.append(char)
        return "".join(chars)


class SMILESDataset(Dataset):
    """Dataset for SMILES sequences"""

    def __init__(self, smiles_list, targets=None, tokenizer=None, max_length=200):
        self.smiles_list = smiles_list
        self.targets = targets
        self.tokenizer = tokenizer
        self.max_length = max_length
        # Reject unusable labels up front. A blank Tc cell arrives as NaN,
        # which torch happily wraps in a tensor; the first batch containing it
        # NaNs every weight and the run only fails later, inside sklearn, with
        # no hint that one empty cell caused it.
        if targets is not None:
            for i, t in enumerate(targets):
                try:
                    t_float = float(t)
                except (TypeError, ValueError):
                    raise ValueError(f"Target at row {i} is not numeric: {t!r}")
                if not math.isfinite(t_float):
                    raise ValueError(f"Target at row {i} is not finite: {t!r}")
        # START + SMILES + END must fit in max_length; anything longer is
        # silently truncated by encode() and can drop chemically important
        # tails (e.g. a polymer attachment point). Warn once at construction.
        n_trunc = 0
        longest = 0
        for s in smiles_list:
            n = len(s) if isinstance(s, str) else 0
            if n > longest:
                longest = n
            if n + 2 > max_length:
                n_trunc += 1
        if n_trunc:
            print(
                f"WARNING: {n_trunc} SMILES exceed max_length={max_length} "
                f"(longest string is {longest} chars, needs {longest + 2} "
                f"tokens with <START>/<END>) and will be truncated"
            )

    def __len__(self):
        return len(self.smiles_list)

    def __getitem__(self, idx):
        smiles = self.smiles_list[idx]
        encoded = self.tokenizer.encode(smiles, self.max_length)
        encoded_tensor = torch.tensor(encoded, dtype=torch.long)
        if self.targets is not None:
            target = torch.tensor([float(self.targets[idx])], dtype=torch.float)
            return encoded_tensor, target
        else:
            return encoded_tensor


# ===== src/data/graph_features.py =====

import math

from rdkit import Chem
import torch
from torch_geometric.data import Data

# Width of the per-bond feature vector built in smiles_to_graph. Needed to shape
# an empty edge_attr for molecules that have no bonds at all (a single atom, e.g.
# "C" or "[Na+]"), where the bond loop never runs and there is no sample vector
# to measure. Keep in step with the `bond_feat` list below.
BOND_FEATURE_DIM = 21

# Shortest-path distances are >= 0. The previous sentinel (10.0) collided with a
# real 10-bond path, so "no * in this fragment" looked identical to "ten bonds
# from *". Negative is reserved for missing.
NO_ATTACHMENT_PATH = -1.0


def is_carbonyl_carbon(atom, mol):
    """Carbonyl carbon: C=O"""
    if atom.GetAtomicNum() != 6:
        return False
    for neighbor in atom.GetNeighbors():
        if neighbor.GetAtomicNum() == 8:
            bond = mol.GetBondBetweenAtoms(atom.GetIdx(), neighbor.GetIdx())
            if bond.GetBondType() == Chem.rdchem.BondType.DOUBLE:
                return True
    return False


def is_carboxyl_carbon(atom, mol):
    """Carboxyl carbon: C(=O)OH"""
    if not is_carbonyl_carbon(atom, mol):
        return False
    oh_count = 0
    for neighbor in atom.GetNeighbors():
        # MolFromSmiles leaves hydrogens implicit, so looking for an explicit
        # H *atom* among the oxygen's neighbours never matches. Ask the
        # oxygen how many hydrogens it carries instead.
        if neighbor.GetAtomicNum() == 8 and neighbor.GetTotalNumHs(includeNeighbors=True) > 0:
            oh_count += 1
    return oh_count > 0


def _get_attachment_distance(atom, mol):
    """Shortest-path distance to the nearest attachment point (`*`).

    Returns 0.0 when this atom *is* an attachment point, and
    ``NO_ATTACHMENT_PATH`` (-1) when there is no `*` or no path to one
    (a disconnected fragment in a '.'-separated SMILES).
    """
    try:
        if atom.GetAtomicNum() == 0:
            return 0.0

        attachment_atoms = [a for a in mol.GetAtoms() if a.GetAtomicNum() == 0]
        if not attachment_atoms:
            return NO_ATTACHMENT_PATH

        min_distance = float("inf")
        for attachment in attachment_atoms:
            try:
                distance = Chem.rdmolops.GetShortestPath(mol, atom.GetIdx(), attachment.GetIdx())
                # GetShortestPath returns an EMPTY tuple (not None) when the two
                # atoms live in disconnected fragments. Treat empty / degenerate
                # paths as "no path" so the -1 sentinel applies.
                if distance:
                    path_length = len(distance) - 1
                    if 0 <= path_length < min_distance:
                        min_distance = path_length
            except Exception:
                try:
                    visited = set()
                    queue = [(atom.GetIdx(), 0)]
                    visited.add(atom.GetIdx())
                    while queue:
                        current_idx, dist = queue.pop(0)
                        if current_idx == attachment.GetIdx():
                            if dist < min_distance:
                                min_distance = dist
                            break
                        current_atom = mol.GetAtomWithIdx(current_idx)
                        for neighbor in current_atom.GetNeighbors():
                            neighbor_idx = neighbor.GetIdx()
                            if neighbor_idx not in visited:
                                visited.add(neighbor_idx)
                                queue.append((neighbor_idx, dist + 1))
                except Exception:
                    continue

        return float(min_distance) if min_distance != float("inf") else NO_ATTACHMENT_PATH
    except Exception:
        return NO_ATTACHMENT_PATH


def _is_potential_crosslink_bond(atom1, atom2, mol):
    """Check if this bond could be involved in polymer crosslinking"""
    try:
        aromatic_bond = atom1.GetIsAromatic() or atom2.GetIsAromatic()
        high_degree = atom1.GetTotalDegree() > 3 or atom2.GetTotalDegree() > 3
        heteroatom_bond = atom1.GetAtomicNum() not in [1, 6] or atom2.GetAtomicNum() not in [1, 6]
        return int(aromatic_bond or high_degree or heteroatom_bond)
    except:
        return 0


def _has_attachment_neighbor(atom, mol):
    """Check if atom has an attachment point (*) as a neighbor"""
    try:
        for neighbor in atom.GetNeighbors():
            if neighbor.GetAtomicNum() == 0:
                return True
        return False
    except:
        return False


def smiles_to_graph(smiles_str, atom_map, y_val=None):
    """
    Converts a SMILES string into a PyTorch Geometric Data object.
    Returns a zero-filled graph if the SMILES cannot be featurized.

    An unusable *target*, by contrast, raises: a bad label is a data error,
    not a molecule to be tolerated. Fabricating 0.0 for an unparseable value
    (e.g. a censored ``<0.05``) hides it inside the real Tc range, and
    letting NaN through NaNs every weight on the first batch and only
    surfaces much later as a sklearn "Input contains NaN" error.
    """
    y_float = None
    if y_val is not None:
        try:
            y_float = float(y_val)
        except (TypeError, ValueError):
            raise ValueError(f"Target for SMILES {smiles_str!r} is not numeric: {y_val!r}")
        if not math.isfinite(y_float):
            raise ValueError(f"Target for SMILES {smiles_str!r} is not finite: {y_val!r}")

    def create_zero_graph():
        x = torch.zeros((1, len(atom_map) + 12), dtype=torch.float)
        edge_index = torch.empty((2, 0), dtype=torch.long)
        edge_attr = torch.empty((0, BOND_FEATURE_DIM), dtype=torch.float)
        if y_float is not None:
            y_tensor = torch.tensor([[y_float]], dtype=torch.float)
            return Data(
                x=x, edge_index=edge_index, edge_attr=edge_attr, y=y_tensor, smiles=str(smiles_str)
            )
        else:
            return Data(x=x, edge_index=edge_index, edge_attr=edge_attr, smiles=str(smiles_str))

    try:
        if not isinstance(smiles_str, str) or not smiles_str.strip():
            return create_zero_graph()
        if not isinstance(atom_map, dict) or not atom_map:
            return create_zero_graph()

        mol = Chem.MolFromSmiles(smiles_str)
        if mol is None or mol.GetNumAtoms() == 0:
            return create_zero_graph()

        # Node Features
        node_features = []
        for atom in mol.GetAtoms():
            try:
                symbol = atom.GetSymbol()
                features = [0] * len(atom_map)
                if symbol in atom_map:
                    features[atom_map[symbol]] = 1
                features.extend(
                    [
                        atom.GetAtomicNum(),
                        atom.GetTotalDegree(),
                        atom.GetFormalCharge(),
                        atom.GetTotalNumHs(includeNeighbors=True),
                        atom.GetNumRadicalElectrons(),
                        int(atom.GetIsAromatic()),
                        int(atom.IsInRing()),
                        int(atom.GetHybridization() == Chem.rdchem.HybridizationType.SP),
                        int(atom.GetHybridization() == Chem.rdchem.HybridizationType.SP2),
                        int(atom.GetHybridization() == Chem.rdchem.HybridizationType.SP3),
                        int(atom.GetHybridization() == Chem.rdchem.HybridizationType.S),
                        int(atom.GetHybridization() == Chem.rdchem.HybridizationType.UNSPECIFIED),
                    ]
                )
                node_features.append(features)
            except:
                return create_zero_graph()

        if not node_features:
            return create_zero_graph()

        try:
            x = torch.tensor(node_features, dtype=torch.float)
        except:
            return create_zero_graph()

        # Edge Index and Features
        edge_indices, edge_attrs = [], []
        try:
            for bond in mol.GetBonds():
                i, j = bond.GetBeginAtomIdx(), bond.GetEndAtomIdx()
                if i >= mol.GetNumAtoms() or j >= mol.GetNumAtoms():
                    continue
                edge_indices.extend([(i, j), (j, i)])
                bt = bond.GetBondType()
                stereo = bond.GetStereo()
                atom1 = bond.GetBeginAtom()
                atom2 = bond.GetEndAtom()
                angles_1 = len([n for n in atom1.GetNeighbors() if n.GetIdx() != atom2.GetIdx()])
                angles_2 = len([n for n in atom2.GetNeighbors() if n.GetIdx() != atom1.GetIdx()])
                dist_1 = float(_get_attachment_distance(atom1, mol))
                dist_2 = float(_get_attachment_distance(atom2, mol))

                # Direction-independent part of the bond vector.
                shared_head = [
                    int(bt == Chem.rdchem.BondType.SINGLE),
                    int(bt == Chem.rdchem.BondType.DOUBLE),
                    int(bt == Chem.rdchem.BondType.TRIPLE),
                    int(bt == Chem.rdchem.BondType.AROMATIC),
                    int(bt == Chem.rdchem.BondType.DATIVE),
                    int(stereo == Chem.rdchem.BondStereo.STEREONONE),
                    int(stereo == Chem.rdchem.BondStereo.STEREOZ),
                    int(stereo == Chem.rdchem.BondStereo.STEREOE),
                    int(stereo == Chem.rdchem.BondStereo.STEREOCIS),
                    int(stereo == Chem.rdchem.BondStereo.STEREOTRANS),
                    int(stereo == Chem.rdchem.BondStereo.STEREOANY),
                    int(bond.IsInRing()),
                    int(bond.GetIsConjugated()),
                ]
                shared_mid = [
                    float(min(angles_1, angles_2)),
                    float(max(angles_1, angles_2)),
                ]
                shared_tail = [
                    int(_is_potential_crosslink_bond(atom1, atom2, mol)),
                    int(
                        _has_attachment_neighbor(atom1, mol) or _has_attachment_neighbor(atom2, mol)
                    ),
                ]

                # The four per-atom slots are keyed to RDKit's begin/end
                # assignment, which follows the order the atoms appear in the
                # input string. Emitting the same vector for both directed
                # copies therefore made slot meaning depend on how the SMILES
                # happened to be written, and left the model unable to tell
                # whether a slot describes the edge's source or destination.
                # Order them source-first per direction instead.
                edge_attrs.extend(
                    [
                        shared_head
                        + [float(angles_1), float(angles_2)]
                        + shared_mid
                        + [dist_1, dist_2]
                        + shared_tail,
                        shared_head
                        + [float(angles_2), float(angles_1)]
                        + shared_mid
                        + [dist_2, dist_1]
                        + shared_tail,
                    ]
                )
        except:
            edge_indices, edge_attrs = [], []

        try:
            if edge_indices:
                edge_index = torch.tensor(edge_indices, dtype=torch.long).t().contiguous()
                edge_attr = torch.tensor(edge_attrs, dtype=torch.float)
            else:
                edge_index = torch.empty((2, 0), dtype=torch.long)
                edge_attr = torch.empty((0, BOND_FEATURE_DIM), dtype=torch.float)
        except:
            return create_zero_graph()

        try:
            if y_float is not None:
                y_tensor = torch.tensor([[y_float]], dtype=torch.float)
                return Data(
                    x=x, edge_index=edge_index, edge_attr=edge_attr, y=y_tensor, smiles=smiles_str
                )
            else:
                return Data(x=x, edge_index=edge_index, edge_attr=edge_attr, smiles=smiles_str)
        except:
            return create_zero_graph()
    except:
        return create_zero_graph()


# ===== src/data/loader.py =====

import os

import numpy as np
import pandas as pd
from rdkit import Chem

# stripped intra-package import: from .smiles_data import SMILESTokenizer


def _training_smiles(input_path, smiles_col="SMILES"):
    """Collect SMILES from ``train.csv`` only.

    The atom map and tokenizer must not see ``test.csv``: those rows are the
    held-out scoring set. ``valid.csv`` is no longer part of the layout (it was
    merged into train.csv) and is ignored here, matching :func:`load_split`.
    Unseen symbols at score time get an all-zero one-hot / ``<UNK>``.
    """
    path = os.path.join(input_path, "train.csv")
    df = pd.read_csv(path)
    return df[smiles_col].tolist()


def build_atom_map_from_smiles(smiles_iter):
    """Build atom map from any iterable of SMILES strings.

    Used by the notebook pipeline (via ``train.csv``) and by the DRUM
    ``custom.fit`` hook (via the in-memory training frame). Test SMILES never
    contribute atom types.
    """
    atoms_set = set()
    n_invalid = 0
    for s in smiles_iter:
        if not isinstance(s, str):
            n_invalid += 1
            continue
        try:
            mol = Chem.MolFromSmiles(s)
        except Exception:
            n_invalid += 1
            continue
        if mol is None:
            n_invalid += 1
            continue
        for atom in mol.GetAtoms():
            atoms_set.add(atom.GetSymbol())
    if n_invalid:
        # smiles_to_graph turns each of these into the same all-zero one-node
        # graph while keeping its real target, so the model is fit against
        # contradictory labels on an identical input. Say how many.
        print(
            f"WARNING: {n_invalid} SMILES could not be parsed by RDKit and will "
            f"featurize as empty graphs"
        )
    return {atom: idx for idx, atom in enumerate(sorted(atoms_set))}


def build_tokenizer_from_smiles(smiles_iter):
    """Fit a SMILESTokenizer on any iterable of SMILES strings."""
    print("Fitting tokenizer...")
    tokenizer = SMILESTokenizer()
    tokenizer.fit(list(smiles_iter))
    return tokenizer


def _smiles_col(cfg):
    return cfg.get("data", {}).get("smiles_column", "SMILES")


def load_split(cfg):
    """Load the train and test CSVs.

    There is no separate ``valid.csv`` any more - the old validation rows were
    merged into ``train.csv``. Carve a validation set out of the training frame
    with :func:`split_train_valid`.

    Returns:
        (train_df, test_df)
    """
    input_path = cfg["paths"]["input"]

    train_df = pd.read_csv(os.path.join(input_path, "train.csv"))
    test_df = pd.read_csv(os.path.join(input_path, "test.csv"))

    print(f"Loaded data from {input_path}:")
    print(f"  train: {len(train_df)}, test: {len(test_df)}")

    return train_df, test_df


def load_or_split(cfg):
    """Backwards-compatible alias for :func:`load_split`."""
    return load_split(cfg)


def split_train_valid(train_df, cfg, valid_ratio=None):
    """Randomly carve a validation set out of ``train_df``.

    Default ratio comes from ``cfg['data']['valid_ratio']`` (0.2 -> a 4:1
    train/valid split). The split is seeded with ``cfg['seed']`` so stage 1 of
    the notebook is reproducible.

    Returns:
        (sub_train_df, valid_df)
    """
    if valid_ratio is None:
        valid_ratio = cfg.get("data", {}).get("valid_ratio", 0.2)

    rng = np.random.RandomState(cfg.get("seed", 42))
    idx = rng.permutation(len(train_df))
    n_valid = int(round(len(train_df) * valid_ratio))

    valid_idx = idx[:n_valid]
    train_idx = idx[n_valid:]

    sub_train_df = train_df.iloc[train_idx].reset_index(drop=True)
    valid_df = train_df.iloc[valid_idx].reset_index(drop=True)

    print(
        f"Split train.csv {1 - valid_ratio:.0%}/{valid_ratio:.0%}: "
        f"train {len(sub_train_df)}, valid {len(valid_df)}"
    )

    return sub_train_df, valid_df


def build_atom_map(cfg):
    """Build atom map for GNN pipeline (honours data.smiles_column)."""
    return build_atom_map_from_smiles(_training_smiles(cfg["paths"]["input"], _smiles_col(cfg)))


def build_tokenizer(cfg):
    """Build and fit tokenizer for sequence pipeline (honours data.smiles_column)."""
    return build_tokenizer_from_smiles(_training_smiles(cfg["paths"]["input"], _smiles_col(cfg)))


# ===== src/models/_scatter.py =====

"""`scatter_add` without a hard dependency on ``torch_scatter``.

``torch_scatter`` ships compiled C++/CUDA extensions whose wheel must match the
exact torch build (and CUDA toolkit) of the environment. When it doesn't, the
import fails *at load time* of the shared object, e.g. on DataRobot Notebooks::

    OSError: Could not load this library:
        .../site-packages/torch_scatter/_scatter_cuda.so

That is an ``OSError``, not an ``ImportError``, so both have to be caught.

Fallbacks, in order:
1. ``torch_scatter.scatter_add`` — used when it imports cleanly.
2. ``torch_geometric.utils.scatter(..., reduce="sum")`` — PyG >= 2.3, numerically
   identical to (1).
3. A pure-torch ``Tensor.scatter_add_`` implementation — no extra deps at all.
"""
import torch


def _scatter_add_torch(src, index, dim=0, dim_size=None):
    """Pure-torch equivalent of ``torch_scatter.scatter_add``."""
    if dim < 0:
        dim = src.dim() + dim
    if dim_size is None:
        dim_size = int(index.max()) + 1 if index.numel() > 0 else 0

    size = list(src.shape)
    size[dim] = dim_size
    out = torch.zeros(size, dtype=src.dtype, device=src.device)

    view_shape = [1] * src.dim()
    view_shape[dim] = -1
    idx = index.view(view_shape).expand_as(src)
    return out.scatter_add_(dim, idx, src)


try:
    from torch_scatter import scatter_add  # noqa: F401 - fast path when usable
except (ImportError, OSError):  # broken/mismatched C++ extension counts as OSError
    try:
        from torch_geometric.utils import scatter as _pyg_scatter

        def scatter_add(src, index, dim=0, dim_size=None):
            return _pyg_scatter(src, index, dim=dim, dim_size=dim_size, reduce="sum")

    except ImportError:
        scatter_add = _scatter_add_torch

# ===== src/models/pooling.py =====

import math

import torch
import torch.nn as nn
from torch_geometric.utils import softmax

# stripped intra-package import: from ._scatter import scatter_add


class AttentionPooling(nn.Module):
    """Attention-based pooling for molecular graphs"""

    def __init__(self, hidden_dim, num_heads=1, dropout=0.1):
        super().__init__()
        self.hidden_dim = hidden_dim
        self.num_heads = num_heads
        self.head_dim = hidden_dim // num_heads

        assert hidden_dim % num_heads == 0, "hidden_dim must be divisible by num_heads"

        self.query = nn.Linear(hidden_dim, hidden_dim)
        self.key = nn.Linear(hidden_dim, hidden_dim)
        self.value = nn.Linear(hidden_dim, hidden_dim)

        self.dropout = nn.Dropout(dropout)
        self.scale = math.sqrt(self.head_dim)

    def forward(self, x, batch):
        batch_size = int(batch.max().item()) + 1
        num_nodes = x.size(0)
        H, d = self.num_heads, self.head_dim

        # Lay the heads out first: [N, hidden] -> [H, N, d]. Keeping the node
        # dimension inside (i.e. [N, H, d]) makes the matmul below produce
        # [N, H, H] and the softmax normalise across heads within one node,
        # which is not attention pooling at all.
        Q = self.query(x).view(num_nodes, H, d).transpose(0, 1)
        K = self.key(x).view(num_nodes, H, d).transpose(0, 1)
        V = self.value(x).view(num_nodes, H, d).transpose(0, 1)

        scores = torch.matmul(Q, K.transpose(-2, -1)) / self.scale  # [H, N, N]

        # A node may only attend to nodes of its own molecule.
        # NOTE: this materialises an [H, N, N] matrix — O(N²·H) memory. That is
        # cheap at this project's scale (batch of 16 molecules ≈ 320 nodes, 1
        # head), but it is the hot spot if batch_size or num_heads grow.
        same_graph = batch.unsqueeze(0) == batch.unsqueeze(1)  # [N, N]
        scores = scores.masked_fill(~same_graph.unsqueeze(0), float("-inf"))

        attn = torch.softmax(scores, dim=-1)  # over nodes of the same graph
        attn = self.dropout(attn)

        attended = torch.matmul(attn, V)  # [H, N, d]
        attended = attended.transpose(0, 1).reshape(num_nodes, self.hidden_dim)

        # Graph-level readout: mean over each graph's nodes. Done with scatter
        # rather than a Python loop so empty graphs still occupy their slot
        # (the old loop skipped them, which silently shifted every later graph).
        summed = scatter_add(attended, batch, dim=0, dim_size=batch_size)
        counts = scatter_add(
            torch.ones(num_nodes, 1, device=x.device, dtype=attended.dtype),
            batch,
            dim=0,
            dim_size=batch_size,
        )
        return summed / counts.clamp(min=1)


class GlobalAttentionPooling(nn.Module):
    """Global attention pooling with learnable query"""

    def __init__(self, hidden_dim, dropout=0.1):
        super().__init__()
        self.attention = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim), nn.Tanh(), nn.Linear(hidden_dim, 1)
        )
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, batch):
        batch_size = batch.max().item() + 1
        attn_logits = self.attention(x).squeeze(-1)
        attn_weights = softmax(attn_logits, batch, dim=0)
        attn_weights = self.dropout(attn_weights.unsqueeze(-1))
        weighted_x = attn_weights * x
        pooled = scatter_add(weighted_x, batch, dim=0, dim_size=batch_size)
        return pooled


class SetToSetPooling(nn.Module):
    """Set2Set pooling for variable-size graphs"""

    def __init__(self, hidden_dim, num_iters=3, num_layers=1):
        super().__init__()
        self.hidden_dim = hidden_dim
        self.num_iters = num_iters

        self.lstm = nn.LSTM(2 * hidden_dim, hidden_dim, num_layers, batch_first=True)
        self.attention = nn.Linear(hidden_dim, hidden_dim)

    def forward(self, x, batch):
        batch_size = batch.max().item() + 1
        h = x.new_zeros(batch_size, self.hidden_dim)
        c = x.new_zeros(batch_size, self.hidden_dim)
        r = x.new_zeros(batch_size, self.hidden_dim)

        for _ in range(self.num_iters):
            h_expanded = h[batch]
            attn_input = self.attention(h_expanded)
            attn_logits = (x * attn_input).sum(dim=-1)
            attn_weights = softmax(attn_logits, batch, dim=0)

            r = scatter_add(attn_weights.unsqueeze(-1) * x, batch, dim=0, dim_size=batch_size)

            q_star = torch.cat([h, r], dim=-1).unsqueeze(1)
            _, (h, c) = self.lstm(q_star, (h.unsqueeze(0), c.unsqueeze(0)))
            h, c = h.squeeze(0), c.squeeze(0)

        return torch.cat([h, r], dim=-1)


# ===== src/models/sequence.py =====

import math

import torch
import torch.nn as nn
import torch.nn.functional as F

# Upper bound for the cached positional table. data.max_length is 200 in the
# shipped config; the table is sliced to the batch's actual length.
_MAX_POSITIONS = 5000


def _sinusoidal_positional_encoding(max_positions, dim):
    """Standard fixed sin/cos positional encoding, shape [max_positions, dim]."""
    position = torch.arange(max_positions, dtype=torch.float).unsqueeze(1)
    div_term = torch.exp(torch.arange(0, dim, 2, dtype=torch.float) * (-math.log(10000.0) / dim))
    pe = torch.zeros(max_positions, dim)
    pe[:, 0::2] = torch.sin(position * div_term)
    # An odd embedding_dim leaves one fewer cosine column than sine column.
    pe[:, 1::2] = torch.cos(position * div_term)[:, : pe[:, 1::2].size(1)]
    return pe


class SequenceNN(nn.Module):
    """
    Configurable sequence-based model for property prediction.
    Supports LSTM, CNN, Transformer, or combinations.
    """

    def __init__(
        self,
        vocab_size,
        embedding_dim=128,
        hidden_dim=256,
        num_layers=2,
        num_heads=8,
        dropout=0.2,
        use_lstm=True,
        use_cnn=True,
        use_transformer=True,
        cnn_kernels=[2],
        pooling="mean",
    ):
        super(SequenceNN, self).__init__()

        self.embedding_dim = embedding_dim
        self.hidden_dim = hidden_dim
        self.use_lstm = use_lstm
        self.use_cnn = use_cnn
        self.use_transformer = use_transformer
        self.pooling = pooling
        # `model.pooling` is one config key shared with the graph pipeline, so
        # a graph-only value like `attention` reaches here. Say what happens
        # instead of quietly routing to a different mode in each branch.
        if pooling not in ("mean", "max", "last"):
            print(
                f"WARNING: pooling={pooling!r} is not a sequence pooling mode "
                f"(mean | max | last); using mean"
            )

        self.embedding = nn.Embedding(vocab_size, embedding_dim, padding_idx=0)
        self.dropout = nn.Dropout(dropout)

        feature_dims = []

        if self.use_lstm:
            # nn.LSTM's dropout only applies between stacked layers; with a
            # single layer it is a no-op and torch warns about it. Pass 0 in
            # that case - behaviour is identical, the warning goes away.
            self.lstm = nn.LSTM(
                embedding_dim,
                hidden_dim,
                num_layers,
                batch_first=True,
                dropout=dropout if num_layers > 1 else 0.0,
                bidirectional=True,
            )
            feature_dims.append(hidden_dim * 2)

        if self.use_cnn:
            self.conv1d_layers = nn.ModuleList(
                [
                    nn.Conv1d(embedding_dim, hidden_dim, kernel_size=k, padding=k // 2)
                    for k in cnn_kernels
                ]
            )
            feature_dims.append(hidden_dim * len(cnn_kernels))

        if self.use_transformer:
            encoder_layer = nn.TransformerEncoderLayer(
                d_model=embedding_dim,
                nhead=num_heads,
                dim_feedforward=hidden_dim * 2,
                dropout=dropout,
                batch_first=True,
            )
            # Nested-tensor fast path + padding masks has been wrong in several
            # 2.x releases (PAD positions leak into the representation). Force
            # the dense path; TypeError covers torch builds that lack the kwarg.
            try:
                self.transformer = nn.TransformerEncoder(
                    encoder_layer, num_layers=num_layers, enable_nested_tensor=False
                )
            except TypeError:
                self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
            # nn.TransformerEncoderLayer carries no notion of position, and
            # self-attention plus the masked-mean readout below are both
            # permutation-invariant - so without this the branch scores any
            # anagram of a SMILES identically, i.e. it is a bag of characters
            # and ring-closure/branch order (the actual connectivity) is
            # invisible. Sinusoidal rather than learned so it adds no
            # parameters and existing checkpoints keep loading.
            self.register_buffer(
                "positional_encoding",
                _sinusoidal_positional_encoding(_MAX_POSITIONS, embedding_dim),
                persistent=False,
            )
            self.attention = nn.MultiheadAttention(
                embedding_dim, num_heads, dropout=dropout, batch_first=True
            )
            feature_dims.append(embedding_dim)

        total_features = sum(feature_dims)
        if total_features == 0:
            raise ValueError("At least one of use_lstm, use_cnn, or use_transformer must be True")

        self.feature_fusion = nn.Sequential(
            nn.Linear(total_features, hidden_dim * 2),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim * 2, hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim, 1),
        )

        print(
            f"Model initialized with: LSTM={use_lstm}, CNN={use_cnn}, "
            f"Transformer={use_transformer}, Total features={total_features}"
        )

    def forward(self, x):
        padding_mask = x == 0

        # Guard against fully padded rows. SMILESTokenizer.encode() always emits
        # <START> and <END>, so such a row cannot come from the normal pipeline -
        # but a caller handing raw tensors can produce one, and a fully masked row
        # makes nn.TransformerEncoder crash (or emit NaN, depending on the code
        # path) and the LSTM mean pooling divide by zero. Unmasking position 0
        # computes on the PAD embedding, which is the zero vector (padding_idx=0):
        # a deterministic "empty molecule" representation, mirroring the
        # zero-graph fallback of the graph pipeline. Real rows are untouched.
        all_pad = padding_mask.all(dim=1)
        if all_pad.any():
            padding_mask[all_pad, 0] = False

        embedded = self.embedding(x)
        embedded = self.dropout(embedded)

        features = []

        if self.use_lstm:
            # Pack so the recurrence never runs over PAD. Without packing, the
            # backward direction of the bidirectional LSTM starts inside the
            # padding, so hidden states at *real* positions - and therefore the
            # pooled features - depend on how much padding follows the sequence.
            lengths = (~padding_mask).sum(dim=1).cpu()
            packed = nn.utils.rnn.pack_padded_sequence(
                embedded, lengths, batch_first=True, enforce_sorted=False
            )
            lstm_out, _ = self.lstm(packed)
            lstm_out, _ = nn.utils.rnn.pad_packed_sequence(
                lstm_out, batch_first=True, total_length=x.size(1)
            )
            mask_expanded = padding_mask.unsqueeze(-1).expand_as(lstm_out)
            if self.pooling == "max":
                # pad_packed_sequence zeroes PAD positions, but LSTM outputs
                # can be negative: max(real, 0_pad) is not max(real). Fill
                # PAD with -inf so a short SMILES is not length-biased.
                lstm_features = lstm_out.masked_fill(mask_expanded, float("-inf")).max(dim=1).values
            elif self.pooling == "last":
                # The LSTM is bidirectional, so lstm_out is [B, L, 2*hidden]:
                # the forward half has consumed the whole sequence at
                # lengths-1, but the backward half runs from the end, so its
                # full-sequence state is at position 0. Taking lengths-1 for
                # both halves left the backward half as the state after a
                # single token - and since encode() always emits <END> last,
                # that was the SAME constant for every molecule.
                lengths = (~padding_mask).sum(dim=1)
                forward, backward = lstm_out.chunk(2, dim=-1)
                last_forward = forward[torch.arange(forward.size(0), device=x.device), lengths - 1]
                lstm_features = torch.cat([last_forward, backward[:, 0]], dim=-1)
            else:
                lstm_masked = lstm_out.masked_fill(mask_expanded, 0)
                lstm_features = (
                    lstm_masked.sum(dim=1) / (~padding_mask).sum(dim=1, keepdim=True).float()
                )
            features.append(lstm_features)

        if self.use_cnn:
            cnn_features = []
            embedded_t = embedded.transpose(1, 2)
            # PAD embeddings are zero vectors, but conv bias + ReLU turn every
            # PAD position into a nonzero constant. Zero / -inf those positions
            # so mean and max never see them. `last` indexes the final real
            # token instead, matching the LSTM branch - previously `last` fell
            # through to mean and the documented pooling mode was a no-op.
            conv_mask = padding_mask.unsqueeze(1)  # [B, 1, L]
            n_real = (~padding_mask).sum(dim=1, keepdim=True).float().clamp(min=1)
            last_idx = n_real.squeeze(1).long() - 1
            batch_idx = torch.arange(embedded.size(0), device=x.device)
            for conv_layer in self.conv1d_layers:
                conv_out = F.relu(conv_layer(embedded_t))
                # Even kernel sizes with padding=k//2 emit L+1 positions; the
                # extra one is a window fully inside the right padding - drop it
                # so the mask lines up.
                conv_out = conv_out[..., : x.size(1)]
                if self.pooling == "max":
                    # ReLU makes this equivalent to filling 0 today, but
                    # filling -inf is the length-invariant max regardless of
                    # the activation (same bug the LSTM branch had).
                    pooled = conv_out.masked_fill(conv_mask, float("-inf")).max(dim=-1).values
                elif self.pooling == "last":
                    pooled = conv_out[batch_idx, :, last_idx]
                else:
                    conv_out = conv_out.masked_fill(conv_mask, 0)
                    pooled = conv_out.sum(dim=-1) / n_real
                cnn_features.append(pooled)
            cnn_features = torch.cat(cnn_features, dim=1)
            features.append(cnn_features)

        if self.use_transformer:
            seq_len = x.size(1)
            if seq_len > self.positional_encoding.size(0):
                raise ValueError(
                    f"sequence length {seq_len} exceeds the positional encoding "
                    f"table ({self.positional_encoding.size(0)})"
                )
            positioned = embedded + self.positional_encoding[:seq_len].unsqueeze(0)
            transformer_out = self.transformer(positioned, src_key_padding_mask=padding_mask)
            mask_expanded = padding_mask.unsqueeze(-1).expand_as(transformer_out)
            if self.pooling == "max":
                transformer_features = (
                    transformer_out.masked_fill(mask_expanded, float("-inf")).max(dim=1).values
                )
            elif self.pooling == "last":
                lengths = (~padding_mask).sum(dim=1)
                transformer_features = transformer_out[
                    torch.arange(transformer_out.size(0), device=x.device), lengths - 1
                ]
            else:
                # Masked mean for the attention query. A plain mean(dim=1)
                # would average PAD positions too, so short SMILES would be
                # dominated by padding and the representation would carry
                # sequence length instead of chemistry.
                transformer_masked = transformer_out.masked_fill(mask_expanded, 0)
                n_real = (~padding_mask).sum(dim=1, keepdim=True).float().clamp(min=1)
                query = (transformer_masked.sum(dim=1) / n_real).unsqueeze(1)
                attended_out, _ = self.attention(
                    query, transformer_out, transformer_out, key_padding_mask=padding_mask
                )
                transformer_features = attended_out.squeeze(1)
            features.append(transformer_features)

        combined_features = torch.cat(features, dim=1)
        output = self.feature_fusion(combined_features)
        return output


# ===== src/models/dmpnn.py =====

import torch
import torch.nn as nn
from torch_geometric.nn import global_add_pool, global_max_pool, global_mean_pool

# stripped intra-package import: from ._scatter import scatter_add

# stripped intra-package import: from .pooling import AttentionPooling, GlobalAttentionPooling, SetToSetPooling

_GRAPH_POOLING_MODES = (
    "mean",
    "max",
    "sum",
    "attention",
    "global_attention",
    "set2set",
)


class EnhancedChemPropDMPNN(nn.Module):
    """Enhanced ChemPropDMPNN with normalization and attention pooling"""

    def __init__(
        self,
        atom_fdim,
        bond_fdim,
        hidden_size=300,
        depth=3,
        dropout=0.0,
        activation="ReLU",
        undirected=False,
        ffn_hidden_size=300,
        ffn_num_layers=2,
        output_size=1,
        use_layer_norm=True,
        use_batch_norm=False,
        use_message_residual=True,
        use_ffn_residual=True,
        pooling="attention",
        attention_heads=4,
        set2set_iters=3,
        init_type="xavier_uniform",
        init_gain=1.0,
        bias_init="zeros",
    ):
        super(EnhancedChemPropDMPNN, self).__init__()

        self.atom_fdim = atom_fdim
        self.bond_fdim = bond_fdim
        self.hidden_size = hidden_size
        self.depth = depth
        self.dropout = dropout
        self.undirected = undirected
        self.use_layer_norm = use_layer_norm
        self.use_batch_norm = use_batch_norm
        self.use_message_residual = use_message_residual
        self.use_ffn_residual = use_ffn_residual

        self.init_type = init_type
        self.init_gain = init_gain
        self.bias_init = bias_init

        if pooling not in _GRAPH_POOLING_MODES:
            print(
                f"WARNING: pooling={pooling!r} is not a graph pooling mode "
                f"(mean | max | sum | attention | global_attention | set2set); "
                f"using mean"
            )
            pooling = "mean"
        self.pooling = pooling

        self.activation = _get_activation(activation)

        self.W_i = nn.Linear(atom_fdim + bond_fdim, hidden_size)

        self.message_layers = nn.ModuleList()
        self.update_layers = nn.ModuleList()
        self.layer_norms = nn.ModuleList()
        self.batch_norms = nn.ModuleList()

        # ChemProp does depth-1 directed message steps, then one atom readout.
        # Allocating `depth` message Linears left message_layers[depth-1] unused
        # but still in the state_dict.
        for _ in range(max(depth - 1, 0)):
            self.message_layers.append(nn.Linear(hidden_size, hidden_size))
        for _ in range(depth):
            self.update_layers.append(nn.Linear(atom_fdim + hidden_size, hidden_size))
            if use_layer_norm:
                self.layer_norms.append(nn.LayerNorm(hidden_size))
            if use_batch_norm:
                self.batch_norms.append(nn.BatchNorm1d(hidden_size))

        if pooling == "attention":
            self.pooling_layer = AttentionPooling(hidden_size, attention_heads, dropout)
            pool_output_dim = hidden_size
        elif pooling == "global_attention":
            self.pooling_layer = GlobalAttentionPooling(hidden_size, dropout)
            pool_output_dim = hidden_size
        elif pooling == "set2set":
            self.pooling_layer = SetToSetPooling(hidden_size, set2set_iters)
            pool_output_dim = 2 * hidden_size
        else:
            self.pooling_layer = None
            pool_output_dim = hidden_size

        self.dropout_layer = nn.Dropout(dropout)

        self.ffn_num_layers = ffn_num_layers
        if ffn_num_layers == 1:
            self.ffn = nn.Sequential(nn.Dropout(dropout), nn.Linear(pool_output_dim, output_size))
            self.ffn_layers = None
            self.ffn_norms = None
        else:
            self.ffn_input = nn.Linear(pool_output_dim, ffn_hidden_size)
            self.ffn_layers = nn.ModuleList()
            self.ffn_layer_norms = nn.ModuleList()
            self.ffn_batch_norms = nn.ModuleList()
            for i in range(ffn_num_layers - 2):
                self.ffn_layers.append(nn.Linear(ffn_hidden_size, ffn_hidden_size))
                if use_layer_norm:
                    self.ffn_layer_norms.append(nn.LayerNorm(ffn_hidden_size))
                if use_batch_norm:
                    self.ffn_batch_norms.append(nn.BatchNorm1d(ffn_hidden_size))
            self.ffn_output = nn.Linear(ffn_hidden_size, output_size)

        self.apply(self._init_weights)

    def _init_weights(self, module):
        if isinstance(module, nn.Linear):
            if self.init_type == "xavier_uniform":
                nn.init.xavier_uniform_(module.weight, gain=self.init_gain)
            elif self.init_type == "xavier_normal":
                nn.init.xavier_normal_(module.weight, gain=self.init_gain)
            elif self.init_type == "kaiming_uniform":
                nn.init.kaiming_uniform_(module.weight, mode="fan_in", nonlinearity="relu")
            elif self.init_type == "kaiming_normal":
                nn.init.kaiming_normal_(module.weight, mode="fan_in", nonlinearity="relu")
            elif self.init_type == "orthogonal":
                nn.init.orthogonal_(module.weight, gain=self.init_gain)
            else:
                nn.init.xavier_uniform_(module.weight, gain=self.init_gain)
            if module.bias is not None:
                if self.bias_init == "zeros":
                    nn.init.zeros_(module.bias)
                elif self.bias_init == "ones":
                    nn.init.ones_(module.bias)
                else:
                    nn.init.zeros_(module.bias)

    def forward(self, data):
        x, edge_index, edge_attr = data.x, data.edge_index, data.edge_attr
        batch = (
            data.batch
            if hasattr(data, "batch") and data.batch is not None
            else torch.zeros(x.size(0), dtype=torch.long, device=x.device)
        )

        # NOTE: no `to_undirected` here. smiles_to_graph already emits both
        # directions of every bond, so it cannot add an edge - but its
        # `coalesce(reduce='add')` silently SUMS each 21-dim bond feature
        # vector with itself. `undirected` is instead handled the way
        # ChemProp does it, by tying the two directed bond states together
        # inside encode_with_normalization.
        node_repr = self.encode_with_normalization(x, edge_index, edge_attr)

        if self.pooling_layer is not None:
            mol_repr = self.pooling_layer(node_repr, batch)
        else:
            if self.pooling == "mean":
                mol_repr = global_mean_pool(node_repr, batch)
            elif self.pooling == "max":
                mol_repr = global_max_pool(node_repr, batch)
            elif self.pooling == "sum":
                mol_repr = global_add_pool(node_repr, batch)
            else:
                # Unknown values are coerced to mean in __init__; this branch
                # is only reached if self.pooling is mutated after construction.
                mol_repr = global_mean_pool(node_repr, batch)

        return self.forward_ffn(mol_repr)

    def encode_with_normalization(self, x, edge_index, edge_attr):
        row, col = edge_index
        bond_input = torch.cat([x[row], edge_attr], dim=1)
        hidden = self.W_i(bond_input)
        hidden = self.activation(hidden)
        hidden = self.dropout_layer(hidden)

        # Twin lookup for the D-MPNN message: edge (v, w) must aggregate the
        # bonds arriving at v *minus* the reverse bond (w, v). Without that
        # subtraction a bond immediately reads back what it sent one step
        # earlier, and - because the remaining sum depends only on `row` -
        # every out-edge of an atom receives an identical message, which
        # collapses the directed formulation into a node-centric one.
        reverse = _reverse_edge_index(edge_index, x.size(0))
        reverse_safe = reverse.clamp(min=0)
        has_reverse = (reverse >= 0).unsqueeze(-1).to(hidden.dtype)

        for layer_idx in range(self.depth - 1):
            if self.undirected:
                # ChemProp's `--undirected`: tie the two directions together.
                hidden = hidden + has_reverse * (hidden[reverse_safe] - hidden) / 2
            hidden_residual = hidden
            nei_message = scatter_add(hidden, col, dim=0, dim_size=x.size(0))
            bond_message = nei_message[row] - has_reverse * hidden[reverse_safe]
            bond_input = torch.cat([x[row], bond_message], dim=1)
            hidden_new = self.message_layers[layer_idx](hidden) + self.update_layers[layer_idx](
                bond_input
            )
            if self.use_layer_norm:
                hidden_new = self.layer_norms[layer_idx](hidden_new)
            if self.use_batch_norm:
                hidden_new = self.batch_norms[layer_idx](hidden_new)
            hidden_new = self.activation(hidden_new)
            hidden_new = self.dropout_layer(hidden_new)
            if self.use_message_residual:
                hidden = hidden_new + hidden_residual
            else:
                hidden = hidden_new

        nei_message = scatter_add(hidden, col, dim=0, dim_size=x.size(0))
        atom_input = torch.cat([x, nei_message], dim=1)
        atom_hidden = self.update_layers[-1](atom_input)
        if self.use_layer_norm:
            atom_hidden = self.layer_norms[-1](atom_hidden)
        if self.use_batch_norm:
            atom_hidden = self.batch_norms[-1](atom_hidden)
        atom_hidden = self.activation(atom_hidden)
        atom_hidden = self.dropout_layer(atom_hidden)
        return atom_hidden

    def forward_ffn(self, x):
        if self.ffn_num_layers == 1:
            return self.ffn(x)

        h = self.ffn_input(x)
        h = self.activation(h)
        h = self.dropout_layer(h)

        for i in range(len(self.ffn_layers)):
            h_residual = h
            h_new = self.ffn_layers[i](h)
            if self.use_layer_norm and i < len(self.ffn_layer_norms):
                h_new = self.ffn_layer_norms[i](h_new)
            if self.use_batch_norm and i < len(self.ffn_batch_norms):
                h_new = self.ffn_batch_norms[i](h_new)
            h_new = self.activation(h_new)
            h_new = self.dropout_layer(h_new)
            if self.use_ffn_residual:
                h = h_new + h_residual
            else:
                h = h_new

        output = self.ffn_output(h)
        return output


def _reverse_edge_index(edge_index, num_nodes):
    """For every directed edge (v, w), the index of its twin (w, v).

    D-MPNN's message for edge (v, w) sums the incoming edges of v *except*
    the reverse edge (w, v), so the twin has to be locatable. Matching on
    (row, col) keys rather than assuming the featurizer's consecutive
    ``[(i, j), (j, i)]`` layout keeps this correct after any reordering
    (PyG batching, ``to_undirected``, hand-built graphs).

    Returns a long tensor of twin indices, ``-1`` where a twin is absent.
    """
    row, col = edge_index
    num_edges = row.numel()
    if num_edges == 0:
        return torch.empty(0, dtype=torch.long, device=row.device)

    keys = row * num_nodes + col
    twins = col * num_nodes + row

    order = torch.argsort(keys)
    sorted_keys = keys[order]
    pos = torch.searchsorted(sorted_keys, twins).clamp(max=num_edges - 1)
    reverse = order[pos]
    return reverse.masked_fill(sorted_keys[pos] != twins, -1)


def _get_activation(activation):
    """Get activation function by name"""
    if activation == "ReLU":
        return nn.ReLU()
    elif activation == "LeakyReLU":
        return nn.LeakyReLU(0.1)
    elif activation == "PReLU":
        return nn.PReLU()
    elif activation == "ELU":
        return nn.ELU()
    elif activation == "tanh":
        return nn.Tanh()
    elif activation == "SELU":
        return nn.SELU()
    elif activation == "GELU":
        return nn.GELU()
    elif activation == "Swish":
        return nn.SiLU()
    else:
        raise ValueError(f"Activation {activation} not supported.")


def create_enhanced_chemprop_dmpnn(data_list, **kwargs):
    """Factory function to create Enhanced ChemPropDMPNN"""
    node_dim = data_list[0].num_node_features
    edge_dim = data_list[0].edge_attr.size(1) if hasattr(data_list[0], "edge_attr") else 0

    model = EnhancedChemPropDMPNN(
        atom_fdim=node_dim,
        bond_fdim=edge_dim,
        hidden_size=kwargs.get("hidden_size", 300),
        depth=kwargs.get("depth", 3),
        dropout=kwargs.get("dropout", 0.1),
        activation=kwargs.get("activation", "ReLU"),
        undirected=kwargs.get("undirected", False),
        ffn_hidden_size=kwargs.get("ffn_hidden_size", 300),
        ffn_num_layers=kwargs.get("ffn_num_layers", 2),
        output_size=kwargs.get("output_size", 1),
        use_layer_norm=kwargs.get("use_layer_norm", True),
        use_batch_norm=kwargs.get("use_batch_norm", False),
        use_message_residual=kwargs.get("use_message_residual", True),
        use_ffn_residual=kwargs.get("use_ffn_residual", True),
        pooling=kwargs.get("pooling", "attention"),
        attention_heads=kwargs.get("attention_heads", 4),
        set2set_iters=kwargs.get("set2set_iters", 3),
        init_type=kwargs.get("init_type", "xavier_uniform"),
        init_gain=kwargs.get("init_gain", 1.0),
        bias_init=kwargs.get("bias_init", "zeros"),
    )
    return model


# ===== src/training/trainer.py =====

import os

import numpy as np
from sklearn.metrics import mean_absolute_error
import torch
from torch.optim import Adam
from torch.utils.data import DataLoader as TorchDataLoader
from torch_geometric.loader import DataLoader as PyGDataLoader

# stripped intra-package import: from ..models.dmpnn import create_enhanced_chemprop_dmpnn
# stripped intra-package import: from ..models.sequence import SequenceNN
# stripped intra-package import: from ..data.smiles_data import SMILESTokenizer, SMILESDataset
# stripped intra-package import: from ..data.graph_features import smiles_to_graph

ARTIFACT_NAME = "smiles_model.pth"


def _parse_model_type(model_type):
    """Parse model type string into (is_graph, sequence_flags)."""
    model_type = model_type.lower().strip()
    if model_type == "dmpnn":
        return True, {}

    parts = set(model_type.split("+"))
    valid = {"lstm", "cnn", "transformer"}
    unknown = parts - valid
    if unknown:
        raise ValueError(
            f"Unknown model type component: {unknown}. "
            f"Valid: dmpnn, lstm, cnn, transformer (combinable with '+')"
        )
    return False, {
        "use_lstm": "lstm" in parts,
        "use_cnn": "cnn" in parts,
        "use_transformer": "transformer" in parts,
    }


def _build_model(cfg, data_list=None, tokenizer=None):
    """Build model based on config. Returns (model, is_graph)."""
    mcfg = cfg["model"]
    is_graph, seq_flags = _parse_model_type(mcfg["type"])

    if is_graph:
        if not data_list:
            raise ValueError("Cannot build a DMPNN model from an empty data_list")
        dmpnn_cfg = mcfg.get("dmpnn", {})
        model = create_enhanced_chemprop_dmpnn(
            data_list,
            hidden_size=mcfg["hidden_dim"],
            depth=dmpnn_cfg.get("depth", 3),
            dropout=mcfg["dropout"],
            activation=dmpnn_cfg.get("activation", "ReLU"),
            undirected=dmpnn_cfg.get("undirected", False),
            ffn_hidden_size=dmpnn_cfg.get("ffn_hidden_size", mcfg["hidden_dim"]),
            ffn_num_layers=dmpnn_cfg.get("ffn_num_layers", 3),
            use_layer_norm=dmpnn_cfg.get("use_layer_norm", False),
            use_batch_norm=dmpnn_cfg.get("use_batch_norm", False),
            use_message_residual=dmpnn_cfg.get("use_message_residual", True),
            use_ffn_residual=dmpnn_cfg.get("use_ffn_residual", False),
            pooling=mcfg.get("pooling", "mean"),
        )
    else:
        seq_cfg = mcfg.get("sequence", {})
        model = SequenceNN(
            vocab_size=len(tokenizer.char_to_idx),
            embedding_dim=seq_cfg.get("embedding_dim", 128),
            hidden_dim=mcfg["hidden_dim"],
            num_layers=seq_cfg.get("num_layers", 1),
            num_heads=seq_cfg.get("num_heads", 4),
            dropout=mcfg["dropout"],
            use_lstm=seq_flags["use_lstm"],
            use_cnn=seq_flags["use_cnn"],
            cnn_kernels=seq_cfg.get("cnn_kernels", [3]),
            use_transformer=seq_flags["use_transformer"],
            pooling=mcfg.get("pooling", "mean"),
        )

    return model, is_graph


def _eval_loader(model, loader, is_graph, device):
    """Run model on a loader. Returns (preds, targets_or_none)."""
    model.eval()
    all_preds = []
    all_true = []
    has_target = None

    with torch.no_grad():
        for batch in loader:
            if is_graph:
                batch = batch.to(device)
                out = model(batch)
                all_preds.append(out.cpu())
                if hasattr(batch, "y") and batch.y is not None:
                    all_true.append(batch.y.cpu())
                    has_target = True
            else:
                if isinstance(batch, (list, tuple)) and len(batch) == 2:
                    x, y = batch
                    x, y = x.to(device), y.to(device)
                    out = model(x)
                    all_preds.append(out.cpu())
                    all_true.append(y.cpu())
                    has_target = True
                else:
                    x = (
                        batch.to(device)
                        if not isinstance(batch, (list, tuple))
                        else batch[0].to(device)
                    )
                    out = model(x)
                    all_preds.append(out.cpu())
                    has_target = False

    if not all_preds:
        # Empty loader (0-row score payload). torch.cat([]) raises.
        return np.zeros((0,), dtype=np.float32), None

    preds = torch.cat(all_preds, dim=0).numpy().reshape(-1)
    if has_target and all_true:
        true = torch.cat(all_true, dim=0).numpy().reshape(-1)
        return preds, true
    return preds, None


def _build_bundle(model, cfg, atom_map=None, tokenizer=None):
    """Assemble the on-disk artifact: state_dict plus everything needed to
    re-featurize new SMILES and rebuild the same model at inference."""
    return {
        "state_dict": {k: v.cpu() for k, v in model.state_dict().items()},
        "cfg": cfg,
        "target": cfg.get("target"),
        "smiles_col": cfg.get("data", {}).get("smiles_column", "SMILES"),
        "atom_map": atom_map,
        "tokenizer_vocab": tokenizer.char_to_idx if tokenizer is not None else None,
    }


def _restore_tokenizer(vocab):
    """Rebuild a SMILESTokenizer from a saved char_to_idx mapping."""
    tok = SMILESTokenizer()
    tok.char_to_idx = dict(vocab)
    tok.idx_to_char = {v: k for k, v in tok.char_to_idx.items()}
    return tok


def run_train(
    train_data,
    valid_data,
    cfg,
    data_list=None,
    tokenizer=None,
    atom_map=None,
    artifact_name=ARTIFACT_NAME,
):
    """Train model on train set, validate on valid set, save best bundle.

    Args:
        train_data: Training data (PyG list or PyTorch Dataset).
        valid_data: Validation data.
        cfg: Config dict.
        data_list: PyG data list for dmpnn feature dim inference. If None, uses train_data.
        tokenizer: Fitted SMILESTokenizer (for sequence models).
        atom_map: Symbol -> index map (for dmpnn). Bundled into the artifact
            so re-featurization at predict time uses the exact same indexing.
        artifact_name: File name to write the bundle under, inside
            ``cfg['paths']['model']``. Override it to keep a holdout-stage
            checkpoint from clobbering the deployable artifact.

    Returns:
        dict with keys: train_preds, valid_preds, train_mae, valid_mae,
        best_epoch, best_val_mae, lr_history, best_model_path
    """
    tcfg = cfg["training"]
    mcfg = cfg["model"]
    model_save_dir = cfg["paths"].get("model", "model/")

    epochs = tcfg["epochs"]
    lr = tcfg["lr"]
    patience = tcfg["early_stopping"]["patience"]
    min_delta = tcfg["early_stopping"]["min_delta"]

    is_graph, _ = _parse_model_type(mcfg["type"])
    if data_list is None:
        data_list = train_data
    if is_graph and not atom_map:
        raise ValueError(
            "atom_map is empty; no valid SMILES were parsed. " "Check RDKit and data.smiles_column."
        )

    DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
    os.makedirs(model_save_dir, exist_ok=True)

    Loader = PyGDataLoader if is_graph else TorchDataLoader

    train_loader = Loader(train_data, batch_size=tcfg["batch_size_train"], shuffle=True)
    valid_loader = Loader(valid_data, batch_size=tcfg["batch_size_valid"], shuffle=False)

    print(f"train: {len(train_data)}, valid: {len(valid_data)}")

    model, _ = _build_model(cfg, data_list=data_list, tokenizer=tokenizer)
    model = model.to(DEVICE)

    optimizer = Adam(model.parameters(), lr=lr)
    # NOTE: no `verbose=` — deprecated in torch 2.2 and removed in later releases
    # (TypeError: ReduceLROnPlateau.__init__() got an unexpected keyword argument
    # 'verbose'). LR is printed every epoch below, plus an explicit note on each drop.
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer,
        mode="min",
        factor=tcfg["scheduler"]["factor"],
        patience=tcfg["scheduler"]["patience"],
        min_lr=tcfg["scheduler"]["min_lr"],
    )
    criterion = getattr(torch.nn, tcfg.get("criterion", "L1Loss"))()

    best_val_mae = float("inf")
    best_epoch = 0
    patience_counter = 0
    lr_history = []
    best_model_path = os.path.join(model_save_dir, artifact_name)

    for epoch in range(1, epochs + 1):
        model.train()
        total_loss = 0
        n_samples = 0

        for batch in train_loader:
            optimizer.zero_grad()
            if is_graph:
                batch = batch.to(DEVICE)
                out = model(batch)
                loss = criterion(out, batch.y)
                bs = batch.num_graphs
            else:
                x, y = batch
                x, y = x.to(DEVICE), y.to(DEVICE)
                out = model(x)
                loss = criterion(out, y)
                bs = x.size(0)

            loss.backward()
            optimizer.step()
            total_loss += loss.item() * bs
            n_samples += bs

        train_loss = total_loss / n_samples

        # Validation
        valid_preds, valid_true = _eval_loader(model, valid_loader, is_graph, DEVICE)
        valid_mae = mean_absolute_error(valid_true, valid_preds)

        epoch_lr = optimizer.param_groups[0]["lr"]
        lr_history.append(epoch_lr)
        scheduler.step(valid_mae)
        next_lr = optimizer.param_groups[0]["lr"]

        # Report the LR this epoch actually trained at. Printing the value the
        # scheduler had just installed made every drop appear one epoch early,
        # so this log disagreed with stage 2's replay of lr_history - which
        # made a correct replay look broken.
        print(
            f"Epoch: {epoch:02d}, Train Loss: {train_loss:.4f}, "
            f"Valid MAE: {valid_mae:.4f}, LR: {epoch_lr:.2e}"
        )
        if next_lr < epoch_lr:
            print(f"  LR reduced: {epoch_lr:.2e} -> {next_lr:.2e} (from the next epoch)")

        if valid_mae < best_val_mae - min_delta:
            best_val_mae = valid_mae
            best_epoch = epoch
            patience_counter = 0
            torch.save(
                _build_bundle(model, cfg, atom_map=atom_map, tokenizer=tokenizer),
                best_model_path,
            )
            print(f"  -> New best: {best_val_mae:.4f}")
        else:
            patience_counter += 1
            if patience_counter % 20 == 0 or patience_counter >= patience - 5:
                print(f"  No improvement. Patience: {patience_counter}/{patience}")

        if patience_counter >= patience:
            print(f"Early stopping at epoch {epoch}")
            break

    if best_epoch == 0:
        # Nothing beat the initial `inf`, i.e. validation MAE was NaN or
        # infinite in every epoch. Fail here rather than fall through: the
        # old `os.path.exists` check would happily load a LEFTOVER checkpoint
        # from an earlier run and the metrics printed below would describe
        # that model instead of this run.
        raise RuntimeError(
            "Training produced no usable checkpoint: validation MAE was NaN or "
            "infinite in every epoch. Check the target column for missing or "
            "non-numeric values, and the learning rate."
        )

    # Reload best weights (from the bundle this run saved).
    bundle = torch.load(best_model_path, map_location=DEVICE, weights_only=False)
    model.load_state_dict(bundle["state_dict"])
    print(f"Loaded best model (valid MAE: {best_val_mae:.4f})")

    # Final evaluation on train and valid. Do NOT reuse train_loader:
    # it was built with shuffle=True, so train_preds would not line up
    # with the input row order (run_train_full already uses a fresh
    # unshuffled loader for the same reason).
    eval_train_loader = Loader(train_data, batch_size=tcfg["batch_size_valid"], shuffle=False)
    train_preds, train_true = _eval_loader(model, eval_train_loader, is_graph, DEVICE)
    valid_preds, valid_true = _eval_loader(model, valid_loader, is_graph, DEVICE)

    train_mae = mean_absolute_error(train_true, train_preds)
    valid_mae = mean_absolute_error(valid_true, valid_preds)

    print(f"\n=== Final Results ===")
    print(f"Train MAE: {train_mae:.4f}")
    print(f"Valid MAE: {valid_mae:.4f}")
    print(f"Best epoch: {best_epoch}")
    print(f"Model saved: {best_model_path}")

    return {
        "train_preds": train_preds,
        "valid_preds": valid_preds,
        "train_mae": train_mae,
        "valid_mae": valid_mae,
        "best_epoch": best_epoch,
        "best_val_mae": best_val_mae,
        "lr_history": lr_history,
        "best_model_path": best_model_path,
    }


def run_train_full(
    train_data,
    cfg,
    epochs,
    data_list=None,
    tokenizer=None,
    atom_map=None,
    lr_schedule=None,
    artifact_name=ARTIFACT_NAME,
):
    """Refit on the *whole* training set for a fixed number of epochs.

    Stage 2 of the notebook flow: stage 1 holds out a validation split to find
    the epoch at which validation MAE bottoms out; this function then throws the
    holdout back in and reruns for exactly that many epochs. There is no
    validation set here, so there is no early stopping and no "best" checkpoint
    to pick - the model as of the final epoch is what gets saved.

    Args:
        train_data: The full training data (PyG list or PyTorch Dataset).
        cfg: Config dict.
        epochs: Number of epochs to run (the best epoch found in stage 1).
        data_list: PyG data list for dmpnn feature dim inference. If None, uses train_data.
        tokenizer: Fitted SMILESTokenizer (for sequence models).
        atom_map: Symbol -> index map (for dmpnn).
        lr_schedule: Optional per-epoch learning rates recorded by ``run_train``
            (its ``lr_history``). When given, the stage-1 LR trajectory is
            replayed verbatim so the run that produced ``epochs`` is reproduced
            as closely as possible. When None, ``ReduceLROnPlateau`` is stepped
            on the *training* loss instead, since no validation metric exists.
        artifact_name: File name for the saved bundle.

    Returns:
        dict with keys: train_preds, train_mae, epochs, best_model_path
    """
    tcfg = cfg["training"]
    mcfg = cfg["model"]
    model_save_dir = cfg["paths"].get("model", "model/")

    epochs = int(epochs)
    if epochs < 1:
        raise ValueError(f"epochs must be >= 1, got {epochs}")

    lr = tcfg["lr"]

    is_graph, _ = _parse_model_type(mcfg["type"])
    if data_list is None:
        data_list = train_data
    if is_graph and not atom_map:
        raise ValueError(
            "atom_map is empty; no valid SMILES were parsed. " "Check RDKit and data.smiles_column."
        )

    DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
    os.makedirs(model_save_dir, exist_ok=True)

    Loader = PyGDataLoader if is_graph else TorchDataLoader
    train_loader = Loader(train_data, batch_size=tcfg["batch_size_train"], shuffle=True)

    print(f"Refit on full train set: {len(train_data)} samples, {epochs} epochs")

    model, _ = _build_model(cfg, data_list=data_list, tokenizer=tokenizer)
    model = model.to(DEVICE)

    optimizer = Adam(model.parameters(), lr=lr)
    scheduler = None
    if lr_schedule:
        lr_schedule = [float(v) for v in lr_schedule]
        print(
            f"Replaying stage-1 LR schedule "
            f"({lr_schedule[0]:.2e} -> {lr_schedule[min(epochs, len(lr_schedule)) - 1]:.2e})"
        )
    else:
        # No validation metric available - plateau on the training loss instead.
        scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
            optimizer,
            mode="min",
            factor=tcfg["scheduler"]["factor"],
            patience=tcfg["scheduler"]["patience"],
            min_lr=tcfg["scheduler"]["min_lr"],
        )
        print("No LR schedule supplied - stepping ReduceLROnPlateau on train loss")

    criterion = getattr(torch.nn, tcfg.get("criterion", "L1Loss"))()
    model_path = os.path.join(model_save_dir, artifact_name)

    for epoch in range(1, epochs + 1):
        if lr_schedule:
            # Clamp: stage 1 may have stopped earlier than `epochs` (it cannot
            # be shorter than best_epoch, but stay safe) - hold the last LR.
            epoch_lr = lr_schedule[min(epoch, len(lr_schedule)) - 1]
            for group in optimizer.param_groups:
                group["lr"] = epoch_lr

        model.train()
        total_loss = 0
        n_samples = 0

        for batch in train_loader:
            optimizer.zero_grad()
            if is_graph:
                batch = batch.to(DEVICE)
                out = model(batch)
                loss = criterion(out, batch.y)
                bs = batch.num_graphs
            else:
                x, y = batch
                x, y = x.to(DEVICE), y.to(DEVICE)
                out = model(x)
                loss = criterion(out, y)
                bs = x.size(0)

            loss.backward()
            optimizer.step()
            total_loss += loss.item() * bs
            n_samples += bs

        train_loss = total_loss / n_samples

        epoch_lr = optimizer.param_groups[0]["lr"]
        print(f"Epoch: {epoch:02d}/{epochs}, Train Loss: {train_loss:.4f}, " f"LR: {epoch_lr:.2e}")

        if scheduler is not None:
            scheduler.step(train_loss)
            next_lr = optimizer.param_groups[0]["lr"]
            if next_lr < epoch_lr:
                print(f"  LR reduced: {epoch_lr:.2e} -> {next_lr:.2e} " f"(from the next epoch)")

    torch.save(
        _build_bundle(model, cfg, atom_map=atom_map, tokenizer=tokenizer),
        model_path,
    )

    # Fresh unshuffled loader so predictions line up with the input rows.
    eval_loader = Loader(train_data, batch_size=tcfg["batch_size_valid"], shuffle=False)
    train_preds, train_true = _eval_loader(model, eval_loader, is_graph, DEVICE)
    train_mae = mean_absolute_error(train_true, train_preds)

    print(f"\n=== Full-data Refit ===")
    print(f"Epochs: {epochs}")
    print(f"Train MAE: {train_mae:.4f}  (in-sample - not a generalization estimate)")
    print(f"Model saved: {model_path}")

    return {
        "train_preds": train_preds,
        "train_mae": train_mae,
        "epochs": epochs,
        "best_model_path": model_path,
    }


def load_bundle(model_path):
    """Load a bundle saved by run_train / custom.fit."""
    return torch.load(str(model_path), map_location="cpu", weights_only=False)


def _featurize_for_inference(smiles_list, bundle):
    """Reconstruct dataset and the data_list/tokenizer needed by _build_model."""
    cfg = bundle["cfg"]
    is_graph, _ = _parse_model_type(cfg["model"]["type"])

    if is_graph:
        atom_map = bundle["atom_map"]
        if not atom_map:
            raise ValueError("Bundle is missing atom_map; the artifact is not a valid graph model.")
        graphs = [smiles_to_graph(s, atom_map, None) for s in smiles_list]
        return graphs, graphs, None  # eval_data, data_list, tokenizer
    tokenizer = _restore_tokenizer(bundle["tokenizer_vocab"])
    ds = SMILESDataset(
        list(smiles_list),
        None,
        tokenizer,
        max_length=cfg["data"]["max_length"],
    )
    return ds, None, tokenizer


def _predict_with_bundle(smiles_list, bundle):
    """Run inference given an already-loaded bundle. Returns np.ndarray."""
    if len(smiles_list) == 0:
        # Graph models infer input dim from data_list[0]; an empty payload
        # would raise in _build_model before _eval_loader's empty-loader guard.
        return np.zeros((0,), dtype=np.float32)

    cfg = bundle["cfg"]
    is_graph, _ = _parse_model_type(cfg["model"]["type"])

    eval_data, data_list, tokenizer = _featurize_for_inference(smiles_list, bundle)

    DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

    # Build once per loaded bundle. DRUM hands score() the same object that
    # load_model returned on every request, so rebuilding here re-ran Xavier
    # init over the whole network (~550k parameters for the shipped DMPNN)
    # and reprinted the sequence model's init banner on each prediction,
    # only to overwrite it all with load_state_dict microseconds later.
    model = bundle.get("_model")
    if model is None:
        model, _ = _build_model(cfg, data_list=data_list, tokenizer=tokenizer)
        model.load_state_dict(bundle["state_dict"])
        model = model.to(DEVICE)
        bundle["_model"] = model

    Loader = PyGDataLoader if is_graph else TorchDataLoader
    loader = Loader(
        eval_data,
        batch_size=cfg["training"].get("batch_size_test", 128),
        shuffle=False,
    )

    preds, _ = _eval_loader(model, loader, is_graph, DEVICE)
    return preds


def predict(smiles_list, model_path):
    """Predict from a list of SMILES strings using a saved bundle artifact.

    The bundle (written by run_train) carries the cfg, atom_map / tokenizer
    vocabulary, and state_dict needed to rebuild the exact training model
    and re-featurize new inputs identically.

    Returns:
        numpy array of predictions (shape [N]).
    """
    bundle = load_bundle(model_path)
    preds = _predict_with_bundle(smiles_list, bundle)
    print(f"Predicted {len(preds)} samples")
    return preds
