---
# https://github.com/google/yamlfmt config file
continue_on_error: true
formatter:
  include_document_start: true
  retain_line_breaks: true
  max_line_length: 120
exclude:
  - .datarobot/
  - .harness/
